Navbar implementation
fribyte-code/mso-website pull request #2
Opened 2024-10-22 19:20 UTC by KWaloen

Here is the preliminary implementation of the navbar. 

All pages that are created will have a navbar. The links currently navigate to the main page and this should be updated as the pages are developed. 

Gimme feedback please!

![image](https://github.com/user-attachments/assets/dd98bad3-9fd6-4151-a010-94a9e6411ef1)

2024-10-23 09:30 UTC, mathiash98 commented
Code looks good, here is a high resolution image from MSO Trondheim https://i2.wp.com/www.mso-trondheim.no/wp-content/uploads/2023/02/cropped-71212342_318038355703673_8056151426478374912_n.png

You can change the query param `?w=200` to set desired width:
https://i2.wp.com/www.mso-trondheim.no/wp-content/uploads/2023/02/cropped-71212342_318038355703673_8056151426478374912_n.png?w=200

2024-10-23 20:22 UTC, skivdal requested changes
This looks great! There are a couple of small things I'd want cleaned up, but the content itself is great! Thanks for the screenshots also :D

2024-10-23 20:22 UTC, skivdal commented on package-lock.json
Maybe we shouldn't have this file? I don't see a reason for it as this is not a node project

2024-10-23 20:24 UTC, skivdal commented
Also, maybe titlecase 'sign in' (so that it's 'Sign In')?

2024-10-23 20:35 UTC, KWaloen commented on package-lock.json
Ah yes! On the Wagtail website they had written that they use SASS so that was a path that I travelled down. I'll clean that up!

2024-10-29 19:50 UTC, KWaloen commented on home/models.py
> +    return self.get_children().live().public()
Removed!

2024-10-29 20:01 UTC, merged